apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::118102576004:role/UdacityFlaskDeployCBKubectlRole
    username: build
    groups:
      - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::118102576004:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17WTR72MUMFAJ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-30T17:33:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "839"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 63b9746b-4bac-4928-93fc-cf514dfa30fe
